=== hmcts/cpp-context-hearing/hearing-command/hearing-command-handler/src/raml/json/schema/hearing.command.update-hearing-with-inherited-plea.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "offenceId": {
      "$ref": "#/definitions/uuid"
    },
    "caseId": {
      "$ref": "#/definitions/uuid"
    },
    "defendantId": {
      "$ref": "#/definitions/uuid"
    },
    "hearingId": {
      "$ref": "#/definitions/uuid"
    },
    "originHearingId": {
      "$ref": "#/definitions/uuid"
    },
    "pleaDate": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "offenceId",
    "caseId",
    "defendantId",
    "hearingId",
    "originHearingId",
    "pleaDate",
    "value"
  ],
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    }
  }
}

=== hmcts/cpp-context-hearing/hearing-command/hearing-command-handler/src/raml/json/hearing.events.inherited-plea.json
{
  "offenceId": "e085c62c-dc4a-11e7-9296-cec278b6b50a",
  "caseId": "e085c62c-dc4a-11e7-9296-cec278b6b50a",
  "defendantId": "e085c38e-dc4a-11e7-9296-cec278b6b50a",
  "hearingId": "e085c62c-dc4a-11e7-9296-cec278b6b50a",
  "originHearingId": "e085c62c-dc4a-11e7-9296-cec278b6b50a",
  "pleaDate": "2017-01-01",
  "value": "GUILTY"
}
